version: '3'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=jaeger_cluster
      - CASSANDRA_DC=dc1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 5s
      retries: 15
    volumes:
      - my-graphql-app-copy2_cassandra_data:/var/lib/cassandra
    networks:
      - jaeger-network

  cassandra-web:
    image: ipushc/cassandra-web:latest
    ports:
      - "8083:8083"
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
    networks:
      - jaeger-network
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra-init:
    image: cassandra:4.0
    networks:
      - jaeger-network
    depends_on:
      cassandra:
        condition: service_healthy
    command: >
      cqlsh cassandra -e "CREATE KEYSPACE IF NOT EXISTS jaeger_v1_dc1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"

  jaeger-cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.47
    networks:
      - jaeger-network
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    environment:
      - CQLSH_HOST=cassandra
      - KEYSPACE=jaeger_v1_dc1
    command: /cassandra-schema/create.sh

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    networks:
      - jaeger-network
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
      - CASSANDRA_KEYSPACE=jaeger_v1_dc1
      - CASSANDRA_DC=dc1
      - CASSANDRA_PORT=9042
    depends_on:
      jaeger-cassandra-schema:
        condition: service_completed_successfully

networks:
  jaeger-network:
    driver: bridge

volumes:
  my-graphql-app-copy2_cassandra_data:
    external: true